#!/bin/bash

HELP="Usage: lifecap [command]

lifecap captures a stream of events about your life, to feed into summarization
and aggregation systems. The idea is that we use collectors to gather data,
which publish events to topics that other collectors might be interested in.
"
. $(dirname $0)/subcmd.sh


