#!/bin/sh

HELP="Usage: lifecap collector add <name> <path>

Adds a collector. A binary that supports start, stop, status"

. $(dirname $0)/lifecap_lib.sh

name=$1
path=$2

if [ ! -e "$path" ]; then
    echo "$path" does not exist
    exit 1
fi

ln -s $(readlink $path) "$config_dir/collectors/$name"

