#!/bin/sh

HELP="Usage: lifecap job rm <name>

Lists currently installed collectors"

. "$(dirname "$0")"/lifecap_lib.sh

if [ -z "$1" ]; then
    echo "No such job"
    echo "Jobs: $(ls "$config_dir"/collectors)"
fi

path="$config_dir/collectors/$1"

path_exists "$path"

rm "$path"

